import Head from 'next/head';
import Image from 'next/image';
import BannerHome from '../components/BannerHome/BannerHome';
import Header from '../components/Header/Header';
import HomePresentation from '../components/HomePresentation/HomePresentation';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cannaha</title>
        <meta name="description" content="Generated by Cannaha" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <BannerHome />
        <HomePresentation />
      </main>

      <footer>
      </footer>
    </div>
  )
}
